-- ============================================================
-- CAL-ASIA CALIBRATION CERTIFICATE PORTAL
-- PostgreSQL Schema
-- Run this ONCE in pgAdmin 4 Query Tool
-- Database: calasia_certs
-- ============================================================

-- Step 1: Create the database (run in postgres default db first)
-- CREATE DATABASE calasia_certs;
-- Then connect to calasia_certs and run everything below:

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
    id          SERIAL PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(100),
    email       VARCHAR(100),
    phone       VARCHAR(30),
    address     TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id            SERIAL PRIMARY KEY,
    username      VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    role          VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'manager', 'customer')),
    customer_id   INTEGER REFERENCES customers(id) ON DELETE SET NULL,
    email         VARCHAR(100),
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instruments (
    id              SERIAL PRIMARY KEY,
    customer_id     INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    instrument_name VARCHAR(200) NOT NULL,
    serial_number   VARCHAR(100) UNIQUE NOT NULL,
    model           VARCHAR(100),
    manufacturer    VARCHAR(100),
    location        VARCHAR(200),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certificates (
    id                  SERIAL PRIMARY KEY,
    instrument_id       INTEGER NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
    certificate_number  VARCHAR(100) UNIQUE NOT NULL,
    calibration_date    DATE NOT NULL,
    due_date            DATE NOT NULL,
    dropbox_file_path   VARCHAR(500),
    dropbox_shared_link VARCHAR(1000),
    source              VARCHAR(20) DEFAULT 'manual',
    notes               TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_logs (
    id              SERIAL PRIMARY KEY,
    total_files     INTEGER DEFAULT 0,
    success_count   INTEGER DEFAULT 0,
    duplicate_count INTEGER DEFAULT 0,
    unmatched_count INTEGER DEFAULT 0,
    error_count     INTEGER DEFAULT 0,
    triggered_by    VARCHAR(50) DEFAULT 'scheduler',
    message         TEXT,
    synced_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unmatched_files (
    id            SERIAL PRIMARY KEY,
    file_name     VARCHAR(500) NOT NULL,
    dropbox_path  VARCHAR(1000),
    serial_number VARCHAR(100),
    reason        TEXT,
    resolved      BOOLEAN DEFAULT FALSE,
    detected_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS duplicate_files (
    id                 SERIAL PRIMARY KEY,
    file_name          VARCHAR(500) NOT NULL,
    dropbox_path       VARCHAR(1000),
    certificate_number VARCHAR(100),
    reason             TEXT,
    resolved           BOOLEAN DEFAULT FALSE,
    detected_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- DEFAULT ADMIN USER
-- Username: admin
-- Password: Admin@2025
-- (Hash generated by bcrypt)
-- ============================================================
INSERT INTO users (username, password_hash, full_name, role)
VALUES (
    'admin',
    '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ct8WmRUmHB/FMkRkDByKG',
    'System Administrator',
    'admin'
) ON CONFLICT (username) DO NOTHING;

-- ============================================================
-- NOTE: The above hash is for password "Admin@2025"
-- After running schema, use the app's /setup-admin route to reset it
-- ============================================================
